### ISSUE TITLE
Annotation handling

### ISSUE THREAD

**Issue by radekg** [datastrophic/istio-aux#2]
Hey, @akirillov. First of all, thank you for this project. Great work.

While using _istio-aux_, I stumbled on a very specific problem where a pod with an existing `proxy.istio.io/config` annotation would have the annotation replaced by the one from _istio-aux_. Seems to be related to the incorrect use of `meta.Labels` instead of `meta.Annotations` in https://github.com/datastrophic/istio-aux/blob/master/pkg/istio-aux/util.go#L57.

However, if that were working fine, it would surface another problem. A pod with an existing `proxy.istio.io/config` would never have the value of `IstioPodAnnotationValue` set. It would be great if existing `proxy.istio.io/config` value was merged with the `IstioPodAnnotationValue`.

**Comment by radekg** [comment]
PR: https://github.com/datastrophic/istio-aux/pull/1.

**Comment by paul-bormans** [comment]
Just to add; the `proxy.istio.io/config` annotation should be merged with the mesh configuration as defined in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig.

Also for reference to others; with the istio-aux controller enabled, the Prometheus custom scraping setup as defined in https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings is broken. This approach requires the OUTPUT_CERTS environment to be set on the proxy which is pushed over the `proxy.istio.io/config` annotation. With istio-aux overwriting this annotation, the required environment isn't set on the PROXY_CONFIG and the sidecar won't install the certificates.

**Comment by akirillov** [comment]
Hi @radekg, @paul-bormans. Thanks for catching this and for the fix. I think that with the release of Istio Ambient Mesh this project loses actuality but I'm happy to see it helps solve sidecar-based Istio deployments.
